package edu.pja.mas.warehouse.enums;

public enum WarehouseDeliveryStatus {
    AWAITING_PICKUP_ADDRESS,
    AWAITING_DRIVER,
    INVALID_ADDRESS,
    AWAITING_DRIVER_CONFIRMATION,
    DRIVER_REJECTED,
    DRIVER_TIMEOUT,
    IN_TRANSIT,
    AWAITING_UNLOAD,
    UNLOADING,
    COMPLETED
}
